---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - 'vars/certbot-vars.yml'
    - 'vars/nginx-vars.yml'
    - 'vars/postgres-vars.yml'
    - 'vars/nodejs-vars.yml'
    - 'vars/redis-vars.yml'

  roles:
   - user
   - ansible-role-certbot
   - nginx
   - nodesource.node
   - ansible-redis
   - postgresql
   - api

  