sudo: required
dist: bionic
language: node_js
node_js:
  - "12"

services:
  - xvfb
  - postgresql
  - redis

addons:
  chrome: stable
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.4

install:
  - cd client
  - npm i
  - cd ../server
  - npm i

before_script:
  - psql -c 'create database dev;' -U postgres
  - psql -c 'create extension postgis;' -d dev -U postgres

after_script:
  - cd client
  - npm run build
  - npm test
  - cd ../server
  - npm test
