# file: roles/api/tasks/main.yml
---
- name: Install git
  apt: pkg={{item}} state=installed
  with_items:
    - git-core
    - build-essential

- git: repo={{ git_repo }} dest='{{ api_dir }}' version={{git_version}}
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  
- name: Install node packages
  npm: path={{ api_dir }}/server state=latest
  become: yes
  become_user: "{{ ansible_ssh_user }}"

- name: Copy init script
  template: src=api.conf.j2 dest=/etc/init/api.conf mode=0640 owner=root group=root
  notify:
    - restart api
  sudo: yes
