apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30036
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000