certbot_script: letsencrypt
certbot_admin_email: "{{ ssl_admin_email }}"
certbot_create_if_missing: yes
certbot_create_standalone_stop_services: []
certbot_certs:
  - domains:
      - "{{server_name}}"