from: busybox
services:
  - smebberson/alpine-rabbitmq:
      name: rabbitmq
      persist: true
      expose:
        - 5672:5672
  - kiasaki/alpine-postgres:
        name: postgres
        persist: true
        env:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=dev
        expose:
          - 5432:5432
expose:
  - 3000:3000
quiet: false
forward: true
tasks:
  env: env
  clean: npm run clean
  install: env
  test: npm run test
  lint: npm run lint
  build: npm run build
  start: npm start
  ci: .lint .test .build
