---
- name: docker run redis
  docker_container:
    name: redis
    pull: yes
    image: "smebberson/alpine-redis"
    state: started
    recreate: yes
    exposed_ports:
    - "6379"
    published_ports:
    - "6379:6379"
    networks:
    - name: net

  tags:
  - containers
